## Basic Configuration
baseurl = "https://tugboatlabs.dev"
languageCode = "en"

title = "Tugboat Labs"
theme = ["hyde-hyde", "hyde-hyde-modified"]

## Hugo Built-in Features
disqusShortname = "tugboatlabs-dev"
googleAnalytics = "UA-135463566-1"
# enableRobotsTXT = true

# summarylength = 30

#paginate = 5

## Site Settings
[params]
    themeColor = "theme-base-0d"
    author = "Dave Strebel"
    title = "Tugboat Labs"
    # description = "..."
    authorimage = "/img/tugboatlabs.png"
    dateformat = "Jan 2, 2006"

    # sidebar, copyright & license
    copyright = "htr3n"
    license = "CC BY-SA 4.0"
    licenseURL = "https://creativecommons.org/licenses/by-sa/4.0"
    showBuiltWith = false

    # https://highlightjs.org
    highlightjs = true
    highlightjsstyle = "github"
    
    # please choose either GraphComment or Disqus or Utterances
    #GraphCommentId = "..."
    #UtterancesRepo = "..." # https://utteranc.es/
    #UtterancesIssueTerm = "..." # pathname, url, title, og:title
    #UtterancesTheme = "..." # github-light or github-dark

    # Table of contents
    #toc = none, "hugo", or "tocbot"

## Social Accounts
[params.social]
    github = "dstrebel"
    linkedin = "dave-strebel"
    twitter = "#dave_strebel"
    email = "strebeld@gmail.com"
    # gravatar = "your-email@example.com"

## Main Menu
[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 300
    url = "/about/"
